import { Provider } from "react-redux";
import { store } from "../store";
import "../styles/globals.css";
import Header from "../components/Header";
import { Box } from "@mui/material";
import type { AppProps } from "next/app";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Box display="flex" flexDirection="column" className="background-color">
        {" "}
        <Header />
        <Box>
          <Component {...pageProps} />
        </Box>
        <Footer />
      </Box>
    </Provider>
  );
}

export default MyApp;
