import type { AppProps } from 'next/app';
import { Provider } from 'react-redux';
import { store } from '../store'; 
import '../styles/globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { Box } from '@mui/material';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Box display="flex" flexDirection="column" minHeight="100vh">
        <Header />
        <Box flexGrow={1}>
          <Component {...pageProps} />
        </Box>
        <Footer />
      </Box>
    </Provider>
  )
}