import type { AppProps } from "next/app";
import { Provider } from "react-redux";
import { store } from "./store";
import "../styles/globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Box, ThemeProvider } from "@mui/material";
import { theme } from "./styles/themeProvider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <ThemeProvider theme={theme}>
        <Header />
        <Box display="flex" flexDirection="column" height="100vh">
          <Component {...pageProps} />
        </Box>
        <Footer />
      </ThemeProvider>
    </Provider>
  );
}
